import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/analysis_result.dart';

class PDFReportService {
  static Future<void> generateAndDownloadReport(AnalysisResult result) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) => [
          pw.Header(
            level: 0,
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text('GapWise - AI Resume Gap Analysis', style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
                pw.Text('Score: ${result.atsScore}%', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blue)),
              ],
            ),
          ),
          pw.SizedBox(height: 20),
          pw.Header(level: 1, text: 'Resume Strength'),
          pw.Paragraph(text: result.resumeStrength),
          pw.Header(level: 1, text: 'ATS Analysis'),
          pw.Bullet(text: 'ATS Score: ${result.atsScore}/100'),
          pw.Bullet(text: 'Keyword Match: ${result.keywordMatchPercentage}%'),
          pw.Header(level: 1, text: 'Missing Skills'),
          ...result.missingSkills.map((s) => pw.Bullet(text: s)).toList(),
          pw.Header(level: 1, text: 'Weak Skills'),
          ...result.weakSkills.map((s) => pw.Bullet(text: s)).toList(),
          pw.Header(level: 1, text: 'Experience Gap'),
          pw.Paragraph(text: result.experienceGap),
          pw.Header(level: 1, text: 'Suggested Projects'),
          ...result.recommendedProjects.map((p) => pw.Bullet(text: p)).toList(),
          pw.Header(level: 1, text: 'Improvement Suggestions'),
          ...result.improvementSuggestions.map((s) => pw.Bullet(text: s)).toList(),
          pw.Footer(
            margin: const pw.EdgeInsets.only(top: 20),
            padding: const pw.EdgeInsets.only(top: 10),
            decoration: const pw.BoxDecoration(border: pw.Border(top: pw.BorderSide(color: PdfColors.grey))),
            leading: pw.Text('Generated by GapWise AI', style: const pw.TextStyle(color: PdfColors.grey, fontSize: 10)),
          ),
        ],
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'GapWise_Report.pdf',
    );
  }
}
