// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMJaAW--JSUuffVdGIQu0aQbAXI2apPZA',
    appId: '1:971709486990:web:40197bd692106c59cd76df',
    messagingSenderId: '971709486990',
    projectId: 'farm2formula',
    authDomain: 'farm2formula.firebaseapp.com',
    databaseURL: 'https://farm2formula-default-rtdb.firebaseio.com',
    storageBucket: 'farm2formula.firebasestorage.app',
    measurementId: 'G-F7RFY3K3YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8ffAVWYYIo49DzgZt43x-hqSlr8eS748',
    appId: '1:971709486990:android:696795654ce98c53cd76df',
    messagingSenderId: '971709486990',
    projectId: 'farm2formula',
    databaseURL: 'https://farm2formula-default-rtdb.firebaseio.com',
    storageBucket: 'farm2formula.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIHSv82JcNeKXINHLVs_TjnL1qg8ug4Ew',
    appId: '1:971709486990:ios:a49f9f3a3a49ffbfcd76df',
    messagingSenderId: '971709486990',
    projectId: 'farm2formula',
    databaseURL: 'https://farm2formula-default-rtdb.firebaseio.com',
    storageBucket: 'farm2formula.firebasestorage.app',
    iosBundleId: 'com.example.farm2formula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIHSv82JcNeKXINHLVs_TjnL1qg8ug4Ew',
    appId: '1:971709486990:ios:a49f9f3a3a49ffbfcd76df',
    messagingSenderId: '971709486990',
    projectId: 'farm2formula',
    databaseURL: 'https://farm2formula-default-rtdb.firebaseio.com',
    storageBucket: 'farm2formula.firebasestorage.app',
    iosBundleId: 'com.example.farm2formula',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMJaAW--JSUuffVdGIQu0aQbAXI2apPZA',
    appId: '1:971709486990:web:a2274b0e67bed81bcd76df',
    messagingSenderId: '971709486990',
    projectId: 'farm2formula',
    authDomain: 'farm2formula.firebaseapp.com',
    databaseURL: 'https://farm2formula-default-rtdb.firebaseio.com',
    storageBucket: 'farm2formula.firebasestorage.app',
    measurementId: 'G-T6VWCMP1J9',
  );
}
